services:
  web1:
    image: nginx:alpine
    container_name: web1
    volumes:
      - ./web1/index.html:/usr/share/nginx/html/index.html
    networks:
      - webnet

  web2:
    image: nginx:alpine
    container_name: web2
    volumes:
      - ./web2/index.html:/usr/share/nginx/html/index.html
    networks:
      - webnet

  web3:
    image: nginx:alpine
    container_name: web3
    volumes:
      - ./web3/index.html:/usr/share/nginx/html/index.html
    networks:
      - webnet

  loadbalancer:
    image: nginx:alpine
    container_name: nginx_loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2
      - web3
    networks:
      - webnet

networks:
  webnet:
